# logging
logging:
  level:
    root: DEBUG
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    jdbc.resultset: OFF
    jdbc.audit: OFF
    jdbc.sqltiming: OFF
    jdbc.sqlonly: OFF
    jdbc.resultsettable: OFF
    faker: OFF
    org.eclipse.jgit: INFO
    org.apache.http.wire: INFO

# spring
spring:
  output:
    ansi:
      enabled: detect
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password: sa
  sql:
    init:
      mode: embedded
      schema-locations: |
        classpath*:db/core-schema.sql,
        optional:classpath*:schema-${platform}.sql,
        optional:classpath*:schema.sql
      data-locations: |
        classpath*:db/core-data.sql,
        optional:classpath*:data-${platform}.sql,
        optional:classpath*:data.sql
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: none
        show_sql: false
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
  messages:
    basename: /messages/messages
    encoding: UTF-8
    use-code-as-default-message: true
    cache-duration: 10
  mail:
    host: 127.0.0.1
    port: 3025
    username: ~
    password: ~
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true

# mybatis
mybatis:
  configuration:
    cache-enable: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

# jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptorBean
    password: 9gaFqKeH8RhYDY29z8WtvgBy7PpyYw6SWdHzuqhr67L8z23zcqRTqhPMVYv82SkI

# core
core:
  default-locale: en
  supported-Locales:
    - en
    - ko
  data:
    crypto:
      crypto-key-provider:
        bean: defaultCryptoKeyProvider
        properties:
          password: EgBeF!SBkZZm^vTTEzy)^)3b$v*+T#av%DFnk9yvE$jJVP+hB6(VSWkP$Xr%X(NY
          salt: 6c0b434f8ba833bca4340687c1ec8b70
  security:
    authentication-token:
      signing-key: ahD3N&nctCE&aDenBKHu)tav7FyqMw6vPHXRtw7)WbWIvX8Xdtrs4fu*E9UXN58L
      expire-minutes: 60
  storage:
    storage-client:
      bean: defaultStorageClient
      properties:
        location: ./.tmp/storage/
  git:
    location: ./.tmp/git/




