# logging
logging:
  level:
    root: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    jdbc.resultset: OFF
    jdbc.audit: OFF
    jdbc.sqltiming: OFF
    jdbc.sqlonly: OFF
    jdbc.resultsettable: OFF
    faker: OFF

# spring
spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      driver-class-Name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password: ENC(PqzV2jMKXZSYEE/AREcemQ==)
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true

# mybatis
mybatis:
  configuration:
    cache-enable: true
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

# jasypt
jasypt:
  encryptor:
    bean: jasyptEncryptorBean
    password: password

# crypto
crypto:
  key-provider:
    bean: defaultCryptoKeyProvider
    password: EgBeF!SBkZZm^vTTEzy)^)3b$v*+T#av%DFnk9yvE$jJVP+hB6(VSWkP$Xr%X(NY
    salt: 6c0b434f8ba833bca4340687c1ec8b70



