# logging
logging:
  level:
    root: INFO

# spring
spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      driver-class-Name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.0.2:3306/arch4j
      username: arch4j
      password: ENC(rFBJXq2eCLrLhRgJi0gE3Q==)
      minimum-idle: 10
      maximum-pool-size: 20

# core
core:
  storage:
    storage-client:
      properties:
        location: /nfs

